# Generated by Django 5.2.17 on 2026-09-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True)),
                ('sections', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
